### ISSUE TITLE
[doc] Add Contributors Section to Readme.md

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/LocalHarvests#1]
Currently the `Readme.md` looks shabby and not in good shape. We would love if someone could make it more appealing and good looking.

**Comment by Soham1803** [comment]
Can you please specify what kind of changes would you like to have in the ReadME.md file?
And the portion for installing is not very clear, need to put things properly to make it more understandable. You may assign this issue to me.
![image](https://user-images.githubusercontent.com/100792573/231758190-55fd4f80-a18d-4e6a-970f-48324d98259b.png)

**Comment by AmanNegi** [comment]
Sure, I just want it to be more visually appealing like currently the badges look badly formatted also the image format looks boring. I would suggest adding some emotes to the headings. 
![brave_yowugy6Fr6](https://user-images.githubusercontent.com/37607224/231759907-96d27c72-25f9-45fe-8406-f4927d3ed69d.png)

For Installation, you can mention the following steps:
1. Install `Node.js` and clone the repository in your local system.
2. Run `npm install` to fetch all the dependencies.
3. Run `npm run dev` to run the web server. 
4. Go to `localhost:5173` to visit the live website.

Also, it would be great to have two more sections:
- Table of Contents (After screenshots)
- Contributors (At the end of the file)

**Comment by Soham1803** [comment]
***What should be added in the table of contents?***

`This below text is very long and looks exhaustive to read, we should shorten it and add some emojis to make it more readable. What do you think?`

![image](https://user-images.githubusercontent.com/100792573/231777219-df8fb9d5-42b1-42ae-9106-efeff20f4a60.png)

**Comment by AmanNegi** [comment]
Definitely the content can be reduced and made to the point. The table of contents, is just a reference to all the headings so that people can easily switch to different parts of the documentation.

**Comment by Soham1803** [comment]
What content you want to be added under ***table of contents*** section, could you please elaborate?
And for the ***contributors*** section, you will be using all-contributor GitHub app from your side, right to add the contributors?

**Comment by AmanNegi** [comment]
You can skip the table of contents if it's not clear to you. For now you may add the `Contributors`, for reference you can check [this](https://github.com/AmanNegi/AgroMillets) repository.

**Comment by Soham1803** [comment]
I have raised a pull request, please check it.

**Comment by Soham1803** [comment]
Shall I raise a PR, I have made the following changes please check them out, I have considered all your points. 😇

I have just added this table in the tech stack section, taking reference from the repo link you provided me.
![image](https://user-images.githubusercontent.com/100792573/232735937-8e7cff69-9cc5-4892-aa3f-084fc51c235f.png)

And kept the text as it was
![image](https://user-images.githubusercontent.com/100792573/232736402-b534640b-70ba-4bde-9b35-deda48eb9f25.png)

with contributors section
![image](https://user-images.githubusercontent.com/100792573/232736642-56bfc721-bbe6-40eb-8671-b21bbbd3b2cc.png)

**Comment by AmanNegi** [comment]
Good Work! You can raise a new PR, but you can remove the tech stack section as we only use Vite and TailwindCSS. Currently, it's best if you can add the contributor's section

**Comment by Soham1803** [comment]
Okay so, I will keep the upper section as it was before just showing the badges and then raise a PR. Is it fine then?

**Comment by AmanNegi** [comment]
Yes that should be fine.
